# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d22ab1df0f809854423173468d34bac95f7981b4edfb462dbfed3c346cb292ac5791983f7f68edb80f36356b48bebc237a60e516ef93bd15b7c099617f99444

test:
  secret_key_base: dcee4e4c3ff835605dacb05dfc285351ec8a35976f483001cd2ea78edf6ecac3ff86dab9716c1ccf76e4502093efd17dd77517d3a034e1800f4d64ac37343c2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
